### ISSUE TITLE
CPE 스케줄러 확인하기

### ISSUE THREAD

**Issue by yoon-gu** [yoon-gu/epirl#2]
현재 CPE에는 BaseScheduler가 적용되어 있음
tick를 업데이트 하는 방식이 특별하지 않아보임. 
mesa에서 구현되어 있는 Scheduler를 선택해서 ticks 대체해주세요.

1. RandomActivation
2. SimultaneousActivation
3. StagedActivation
4. RandomActivationByType

관련 링크: https://mesa.readthedocs.io/en/latest/apis/time.html

**Comment by kimsol729** [comment]
방금 전 스케줄러를 수정하여 commit and push를 하였는데, "Some jobs were not successful" 이라는 메일이 왔습니다.
위의 Actions 버튼을 눌러서 확인 해 보니 모든python버전에서 뭔가 실패한 것이 있는 듯하나 무엇인지 잘 모르겠습니다.
로컬에서 파이썬 코드는 실행이 잘 되는데 어떤 오류로 메일이 온 건지 알려주시면 감사하겠습니다!
