### ISSUE TITLE
SLIAR + Vaccine Control 수렴 안했던 원인 분석 실험 설계 공유

### ISSUE THREAD

**Issue by yoon-gu** [yoon-gu/epirl#28]
1. 무슨 파라미터를 변경할 건지
2. 변경한 파라미터마다 어떤 값들을 관찰할건지

정해서 답글로 알려주세요~~

**Comment by boyeon-kim** [comment]
**1. 변경된 파라미터 : `eps_start`, `eps_end`, `n_episode`, `reward`**
    궁금한 point : epsilon - greedy 정책은 epsilon이 0 이면 항상 greedy한 정책을 선택 하는 것이 아닌지..? 
                          greedy한 정책만 선택했다면, 올바른 학습이 맞는지..? --> Q-network update에만 의존?_? 

**2. 모두 action(전체 action)과 관련하여 관찰 해야 할 것으로 예상** 
[action 발생 결과 (0 or 1), action value ( Q-network 결과, e-greedy에서 선택하는 action)]
- epsilon 관련 파라미터 - action변화 (range(0:0.2:1) --> 차이가 있는지 check)
[일시적 check 
`eps_start` = 0
<img width="319" alt="image" src="https://user-images.githubusercontent.com/69612871/199399325-b9b84666-b591-4ca9-9762-8319b8ddb57d.png">
`eps_start` = 1
<img width="279" alt="image" src="https://user-images.githubusercontent.com/69612871/199399459-d74742d2-4aff-4d08-83f9-b71cc2f1e25d.png">]
모두 동일한 결과! 

- n_episode : 충분하게 학습되려면 얼마나 많은 episode가 필요한가? 
   (충분한 학습의 기준은 무엇? - 흔들리지 않고 일정한 policy?를 도출하는지?) 
   --> `n_episode` = 2000일 때, 10000번 일 때와 다른 결과를 보임 
   --> 학습시킬 때 중요한 요소는 episode의 갯수 인가? random으로 뽑는 replay buffer에 영향을 끼치는 것으로 예상
   --> 어떤 요소를 관찰하면 이를 확인할 수 있을지 정확히 모르겠습니다 ㅠ_ㅠ

- reward design : 1) - I, 2) -I - Q*u^2 (실제 논문의 cost function)  3) -I - u^2
                              각각의 score 차이, action선택
                              
우선 몇가지 돌려보고 변화하는 것들을 확인해 보았는데, 적절한 요소를 보고 있는 것인지 확신은 없습니다.

**Comment by boyeon-kim** [comment]
> **1. 변경된 파라미터 : `eps_start`, `eps_end`, `n_episode`, `reward`** 궁금한 point : epsilon - greedy 정책은 epsilon이 0 이면 항상 greedy한 정책을 선택 하는 것이 아닌지..? greedy한 정책만 선택했다면, 올바른 학습이 맞는지..? --> Q-network update에만 의존?_?
> 
> **2. 모두 action(전체 action)과 관련하여 관찰 해야 할 것으로 예상** 
> 
> * epsilon 관련 파라미터 - action변화 (range(0:0.2:1) --> 차이가 있는지 check)
>   [일시적 check
>   `eps_start` = 0
> 
> <img alt="image" width="319" src="https://user-images.githubusercontent.com/69612871/199399325-b9b84666-b591-4ca9-9762-8319b8ddb57d.png">
> 
> `eps_start` = 1
> <img alt="image" width="279" src="https://user-images.githubusercontent.com/69612871/199399459-d74742d2-4aff-4d08-83f9-b71cc2f1e25d.png">
> 
> ] 모두 동일한 결과!
> * n_episode : 충분하게 학습되려면 얼마나 많은 episode가 필요한가?
>   (충분한 학습의 기준은 무엇? - 흔들리지 않고 일정한 policy?를 도출하는지?)
>   --> `n_episode` = 2000일 때, 10000번 일 때와 다른 결과를 보임
>   --> 학습시킬 때 중요한 요소는 episode의 갯수 인가? random으로 뽑는 replay buffer에 영향을 끼치는 것으로 예상
>   --> 어떤 요소를 관찰하면 이를 확인할 수 있을지 정확히 모르겠습니다 ㅠ_ㅠ
> * reward design : 1) - I, 2) -I - Q*u^2 (실제 논문의 cost function)  3) -I - u^2
>   각각의 score 차이, action선택
> 
> 우선 몇가지 돌려보고 변화하는 것들을 확인해 보았는데, 적절한 요소를 보고 있는 것인지 확신은 없습니다.

**Comment by yoon-gu** [comment]
> **1. 변경된 파라미터 : `eps_start`, `eps_end`, `n_episode`, `reward`** 궁금한 point : epsilon - greedy 정책은 epsilon이 0 이면 항상 greedy한 정책을 선택 하는 것이 아닌지..? greedy한 정책만 선택했다면, 올바른 학습이 맞는지..? --> Q-network update에만 의존?_?
> 
> **2. 모두 action(전체 action)과 관련하여 관찰 해야 할 것으로 예상**
> 
> * epsilon 관련 파라미터 - action변화 (range(0:0.2:1) --> 차이가 있는지 check)
>   [일시적 check
>   `eps_start` = 0
> 
> <img alt="image" width="319" src="https://user-images.githubusercontent.com/69612871/199399325-b9b84666-b591-4ca9-9762-8319b8ddb57d.png">
> `eps_start` = 1 <img alt="image" width="279" src="https://user-images.githubusercontent.com/69612871/199399459-d74742d2-4aff-4d08-83f9-b71cc2f1e25d.png">
> 
> ] 모두 동일한 결과!
> 
> * n_episode : 충분하게 학습되려면 얼마나 많은 episode가 필요한가?
>   (충분한 학습의 기준은 무엇? - 흔들리지 않고 일정한 policy?를 도출하는지?)
>   --> `n_episode` = 2000일 때, 10000번 일 때와 다른 결과를 보임
>   --> 학습시킬 때 중요한 요소는 episode의 갯수 인가? random으로 뽑는 replay buffer에 영향을 끼치는 것으로 예상
>   --> 어떤 요소를 관찰하면 이를 확인할 수 있을지 정확히 모르겠습니다 ㅠ_ㅠ
> * reward design : 1) - I, 2) -I - Q*u^2 (실제 논문의 cost function)  3) -I - u^2
>   각각의 score 차이, action선택
> 
> 우선 몇가지 돌려보고 변화하는 것들을 확인해 보았는데, 적절한 요소를 보고 있는 것인지 확신은 없습니다.

이 코멘트와 위의 코멘트는 뭐가 다른가요?

**Comment by boyeon-kim** [comment]
앗, 다른게 없습니다! 수정했는데 코멘트가 남아있습니다! 위의 코멘트를 delete하도록 하겠습니다!

**Comment by yoon-gu** [comment]
일단 각 `eps_start`값마다 비교할 결과물들을 그림이나 수치로 나타내주시는게 의사소통에 편하겠네요.

**Comment by boyeon-kim** [comment]
네!

**Comment by boyeon-kim** [comment]
1. 학습이 되지 않았던 이유 분석
(reward design : - I)
   1) print 되는 결과를 보면 다음 action 선택이 없음
   2) 각 inner loop 에서 제대로 loop가 도는 지 확인 
       check(1) : next state, reward, done 
       check(2) : time state
<img width="653" alt="image" src="https://user-images.githubusercontent.com/69612871/200111616-587a2025-acd6-4173-a780-f05675a04712.png">

3. t = 0일 때, 이미 done 조건을 만족해 버림 --> inner loop가 제대로 돌지 않았음!
<img width="670" alt="image" src="https://user-images.githubusercontent.com/69612871/200111681-e5424c59-e594-4ac8-b4e1-317bf078fa57.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/69612871/200111691-2fa0a1ca-4a19-4c9f-a475-270cabb6a3ce.png">

4. result
<img width="510" alt="image" src="https://user-images.githubusercontent.com/69612871/200111710-3c150b41-9724-43a4-aad6-2e02c135665d.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/69612871/200111720-537a137f-d7e4-4505-a30a-ef074b4e98b6.png">

## 학습은 되었으나, 우리가 원하는 결과가 아니다?!

**Comment by yoon-gu** [comment]
![SLIAR_control_u](https://user-images.githubusercontent.com/13851374/200144411-fbc6efdd-0a68-4734-971b-0345c66dfe4c.png)
제가 올린 코드 돌리면 이렇게 나오는데 왜 학습은 되었으나 우리가 원하는 결과가 아니라는 건지 궁금합니다.

**Comment by yoon-gu** [comment]
+ 민영님이랑 일 분담은 어떻게 하고 계시는지도 궁금합니다. 아직 분담을 안하고 있다면 안하고 있다고 알려주세요~~

**Comment by boyeon-kim** [comment]
1. 아, 선배님의 코드를 돌린 것이 아니라 수렴하지 않았던 코드에서 시작하였습니다! 결과가 나온 곳에서 시작하면 어디가 문제인지 제가 인지를 잘 못할 것 같아 그렇게 시작했습니다. 
2. "우리가 원하는 결과가 아니다"라고 하는 것은 선배님의 결과와 다른 결과가 나와서 입니다. 
3. episode의 횟수를 늘리니 동일한 결과가 나온 것은 확인 하였는데, 만약 결과를 몰랐다면 수렴했는지 안했는지 몰랐을텐데 이것을 어떻게 인지하는지 잘 모르겠습니다! 
4. 민영과 일분담은 하지 않고 있습니다!
