### ISSUE TITLE
epsilon Greedy 값을 바꿔가며 그림 비교

### ISSUE THREAD

**Issue by yoon-gu** [yoon-gu/epirl#30]
eps_decay는 고정하고, 

```python
for eps in [0.0, 0.1, 0.2, 0.3, 0.4, ..., 1.0]:
    for n_episodes in [10, 100, 1000, 2000, 5000, 10000]:
         train( )
         save_figure( )
```

eps와 n_episodes는 예제일뿐입니다. 숫자는 임의 조정하셔도 됩니다.

1. 결과마다 SI그래프와 Vaccine 그래프 첨부해주세요.
2. x축: episode, y축: eps 값 (eps의 decay를 그래프로) 그려주세요.

**Comment by boyeon-kim** [comment]
1. eps_start를 0.2 단위로 변경 하였습니다.
- 0.0
![SLIAR_control_u0 010](https://user-images.githubusercontent.com/69612871/201072741-0ff8893a-7c23-4a12-8e7d-efe42e59174a.png)
![SLIAR_control_u0 0100](https://user-images.githubusercontent.com/69612871/201072746-7ca6a425-9552-4ace-9b78-c3c46e351ef7.png)
![SLIAR_control_u0 01000](https://user-images.githubusercontent.com/69612871/201072765-85dc3369-a8e4-4269-b36d-446535b21625.png)
![SLIAR_control_u0 02000](https://user-images.githubusercontent.com/69612871/201072788-c9b50a86-d129-4ace-92ac-f266ccef63f4.png)
![SLIAR_control_u0 05000](https://user-images.githubusercontent.com/69612871/201072807-0ebf3165-2d05-4815-a113-b938e29cf725.png)
![SLIAR_control_u0 010000](https://user-images.githubusercontent.com/69612871/201072817-12972708-c06a-49ba-8006-978644fae43f.png)


- 0.2
- ![SLIAR_control_u0 210](https://user-images.githubusercontent.com/69612871/201072893-307aa548-4892-4705-81a2-f13ec45617d0.png)
![SLIAR_control_u0 2100](https://user-images.githubusercontent.com/69612871/201072898-64c691f5-4839-4e36-b08b-c5a9400727ed.png)
![SLIAR_control_u0 21000](https://user-images.githubusercontent.com/69612871/201072905-9ee84a26-c6eb-415e-a45e-90ccb08053ee.png)
![SLIAR_control_u0 22000](https://user-images.githubusercontent.com/69612871/201072908-c70fe5c3-5f50-472e-a0e8-4d6f17d939c6.png)
![SLIAR_control_u0 25000](https://user-images.githubusercontent.com/69612871/201072911-83b3d017-0dbd-4462-bc95-2862369d14a9.png)
![SLIAR_control_u0 210000](https://user-images.githubusercontent.com/69612871/201073016-611f713f-08c0-41bd-bff2-307f96ee709a.png)


- 0.4
![SLIAR_control_u0 410](https://user-images.githubusercontent.com/69612871/201073097-dcc328e5-e1bd-46bb-bae5-701fff127336.png)
![SLIAR_control_u0 4100](https://user-images.githubusercontent.com/69612871/201073109-20079699-3482-4cba-905e-61fa48484b04.png)
![SLIAR_control_u0 41000](https://user-images.githubusercontent.com/69612871/201073113-9fbe4af3-4cff-4250-852d-d53e6bf2410e.png)
![SLIAR_control_u0 42000](https://user-images.githubusercontent.com/69612871/201073120-79b030a0-5c0f-4253-9a82-9eae952da2bc.png)
![SLIAR_control_u0 45000](https://user-images.githubusercontent.com/69612871/201073125-f6e48189-6e13-4186-b52c-eecfc1babb4a.png)
![SLIAR_control_u0 410000](https://user-images.githubusercontent.com/69612871/201073130-8afb9de0-87b1-48d1-9b4d-64a788570523.png)

- 0.6
![SLIAR_control_u0 610](https://user-images.githubusercontent.com/69612871/201073214-b87f057c-16e5-4b2b-8ce0-72c3ebbd4df6.png)
![SLIAR_control_u0 6100](https://user-images.githubusercontent.com/69612871/201073226-ce2c9206-2d38-4461-8985-3089636f179a.png)
![SLIAR_control_u0 61000](https://user-images.githubusercontent.com/69612871/201073232-a4329da8-2bac-4ebc-b324-56ef50b8ffb8.png)
![SLIAR_control_u0 62000](https://user-images.githubusercontent.com/69612871/201073237-5a45f231-75f7-45ff-a8ea-2affa3dec0b3.png)
![SLIAR_control_u0 65000](https://user-images.githubusercontent.com/69612871/201073240-b2c97ccb-5e9a-4b10-ab4d-1a5f8b48554a.png)

**Comment by yoon-gu** [comment]
이거 슬라이드로 정리해서 내일 발표하시면 됩니다~~~
