### ISSUE TITLE
SLIAR 강화학습 DQN 알고리즘 결과물 분석

### ISSUE THREAD

**Issue by yoon-gu** [yoon-gu/epirl#39]
https://github.com/yoon-gu/epirl/blob/master/rl/dqn/Visualization.ipynb 참고

자유롭게 진행하시면 됩니다.

**Comment by Rabbit739** [comment]
![image](https://user-images.githubusercontent.com/94163977/210508743-65d7cd21-0d9e-42b7-b61e-cb13f010958f.png)
위를 참고하여 SLIAR 모델에 적용중입니다.
1. 중간에 vf, af를 지정할때 크기를 (S,I)가 아닌 (I,S)로 한 이유가 궁금합니다.
2. 현재 총 인구가 S=1000000, I=1 이므로, 1000001의 약수는 9901, 101뿐인데 101을 이용하여 linspace를 102로 우선 설정해보았습니다. 인구에 비해 간격이 너무 넓은 것 같은데, 중간의 수가 없어서 이런 경우에는 그냥 간격이 좁은 것을 선택하여 9902개의 수를 얻는게 맞는지 궁금합니다.

우선 위의 코드로 진행하여 
![image](https://user-images.githubusercontent.com/94163977/210509384-f8fba221-f639-43ab-928e-64530a250cb5.png)
![image](https://user-images.githubusercontent.com/94163977/210509408-d9c22f6e-03e0-48c0-847a-2228edfa6bfd.png)

의 초기 그래프를 얻었습니다. 이후 학습을 통해 이 그래프의 모양이 어떻게 변하는지 관찰할 예정입니다.

**Comment by Rabbit739** [comment]
![image](https://user-images.githubusercontent.com/94163977/210580853-dfdd2ce6-765f-4489-88a6-fb8018dd5fd8.png)
우선 위의 결과로 1000번 학습시킨 결과입니다.

![image](https://user-images.githubusercontent.com/94163977/210581006-90c4653e-97e7-48a5-91d5-283f9bdf1dce.png)
![image](https://user-images.githubusercontent.com/94163977/210581225-84534d60-e8dc-4606-bebc-b20a099cf245.png)
결과가 다음과 같이 바뀌어서 나타났습니다.

학습이 덜 된 것 같아서 횟수를 늘려서 다시 결과를 얻어보겠습니다.

**Comment by Rabbit739** [comment]
약간의 수정을 거쳐 1000번 학습 시켰을 때의 결과를 다시 얻었습니다.
![image](https://user-images.githubusercontent.com/94163977/210714984-1f49f67c-e5e0-466f-ba05-3fc21d2442d0.png)
![image](https://user-images.githubusercontent.com/94163977/210715018-2c5167dd-630b-40d2-865b-3ecf1603b9be.png)

어제와 비슷한 결과가 나왔고, 2000/4000/8000/16000에 대한 결과를 얻는 중입니다.

그런데, 위와 다르게 초기 그래프의 모양이 다르게 나옵니다.
제가 이해한 바로는 vf 값이 value function에서 얻은 값, af값이 맥시멈을 만드는 액션인데, 학습을 전혀 시키지 않은 상태에서는 vf 값이 음수로 나옵니다.(거의)
이게 학습을 시키지 않아서 랜덤 확률로 음수, 양수를 왔다갔다 할 수 있는 건가요? 아니면 뭔가를 잘못이해하거나 코드에 오류가 있는 것일까요..?

![image](https://user-images.githubusercontent.com/94163977/210715435-5c478a9d-1c47-4a65-ac1f-ff37dc794441.png)

**Comment by yoon-gu** [comment]
학습을 전혀하지 않았으므로 이상한 값들이 많이 나오는게 당연합니다.
신경망 모델이 생성 되면 랜덤한 Coefficient들이 할당되므로, 값이 이상하게 되죠. 
학습이 될 수록 덜(?) 이상해질겁니다.

**Comment by Rabbit739** [comment]
![image](https://user-images.githubusercontent.com/94163977/210797318-6e8983c6-21e2-42a1-accb-6c796e49f396.png)
![image](https://user-images.githubusercontent.com/94163977/210797217-e03ba29f-11e1-4bec-acbd-f779e23363a2.png)
![image](https://user-images.githubusercontent.com/94163977/210797265-88f0e918-591b-4232-9e02-a8d675c03f28.png)

16000번 학습한 결과입니다.
확실히 안정되어 있고, 첫번째 그래프에서 백신의 초기 투여가 좋다는 결과는 지난번과 같이 나왔습니다.
dqn을 통해 얻은 두번째 value function에 해당하는 그래프는 S가 크고 I 가 작을수록 안정된다고 보이므로, 학습이 잘 된것으로 판단됩니다.

그런데 문제는 세번째 그래프는 제가 이해하고 있는 것과는 뭔가 다른 것 같습니다.
제가 이해한 바로는, 세번째 그래프는 왼쪽, 즉 S가 매우 작을때만 1이라는 액션을 취해서 백신을 준다라고 이해되는데, 그렇다면 위에서 얻은 첫번째 결과에서 초기에 S가 매우 큰 상황에서 백신을 투여한 것과 상반되지 않나요...?
세번째 그래프를 어떻게 해석해야 좋을지 모르겠습니다...

**Comment by Rabbit739** [comment]
![image](https://user-images.githubusercontent.com/94163977/210905432-13d90692-4fcb-40b2-998c-3b1206bc01a2.png)
visualization이 다른 epsilon 조건 하에서 이상하게 나와서 살펴보는 도중, 이 부분에서 문제가 있지 않나 생각됩니다.
기존의 SIR은 S와 I compartment만 사용하여 모든 경우의 수를 따질 수 있는 반면, SLIAR의 경우는 S,L,I,A의 모든 경우를 따져야 앞과 같이 DQN을 visualization 할 수 있는게 아닐까 라는 생각이 들었습니다.
그렇다면 2차원 그래프를 나타내기가 어려운데 다른 방법을 찾아서 다차원을 표현해야는 것이 맞을까요?

**Comment by yoon-gu** [comment]
애초에 다차원은 시각화하기 거의 불가능합니다. 오늘 세미나 진행하면서 S와 I 외에 필요한 정보가 있는지 교수님께 문의해서 진행하시죠

**Comment by Rabbit739** [comment]
넵 알겠습니다!
