### ISSUE TITLE
Hydra 학습

### ISSUE THREAD

**Issue by Rabbit739** [yoon-gu/epirl#40]
hydra 사용법 학습

**Comment by Rabbit739** [comment]
![image](https://user-images.githubusercontent.com/94163977/210218401-3b67dcf9-3e48-4240-9889-ac96a1e0b8ef.png)
올려주신 파일로 예제 연습 중입니다.
실행하는 방법을 잘 모르겠어서 찾는 중입니다!

**Comment by yoon-gu** [comment]
> ![image](https://user-images.githubusercontent.com/94163977/210218401-3b67dcf9-3e48-4240-9889-ac96a1e0b8ef.png)
> 올려주신 파일로 예제 연습 중입니다.
> 실행하는 방법을 잘 모르겠어서 찾는 중입니다!
> -> 올려주신 예제는 x, y 값 하나만 대입/ multiple run은 여기서는 적용 안됨: SLIAR 모델 수정 필요

멀티런을 하려면 여러개의 인풋을 줘야하는데, 그런 정보가 없으니 안돌아가는겁니다 ㅎㅎ

```bash
$ python opt_example.py x=3,4,5 -m
```

이러면 돌아갈겁니다.

아래 링크 참조하세요.
- https://hydra.cc/docs/tutorials/basic/running_your_app/multi-run/#--multirun--m-from-the-command-line
