### ISSUE TITLE
tex 파일 제작

### ISSUE THREAD

**Issue by Rabbit739** [yoon-gu/epirl#42]
1/6 ppt 파일 변경

**Comment by Rabbit739** [comment]
42-tex-파일-제작 branch 생성 및 Minyoung folder 생성

**Comment by Rabbit739** [comment]
"42-tex-파일-제작"에 tex 파일을 통한 230106doc.pdf 파일 생성했습니다.

**Comment by yoon-gu** [comment]
생성한 파일 이슈에 첨부해주시고, Pull Req 만들어주세요

**Comment by Rabbit739** [comment]
[230106doc.pdf](https://github.com/yoon-gu/epirl/files/10393327/230106doc.pdf)
