### ISSUE TITLE
SLIAR 강화학습 초기 결과 tex 문서화

### ISSUE THREAD

**Issue by yoon-gu** [yoon-gu/epirl#49]

**Comment by yoon-gu** [comment]
이건 진행상황이 어떻게 되나요? 아직 브랜치도 안만들어져서 여쭤봅니다.

**Comment by boyeon-kim** [comment]
코드짜기에서 부터 난항을 겪고 있습니다ㅠ_ㅠ
![IMG_6946](https://user-images.githubusercontent.com/69612871/212027692-737ed6de-f3b3-4a3b-a76f-6b5669dda693.jpg)

이렇게 되는거라고 이해를 하고 있는데, action size가 4가 되는게 아니라, 
(0,1)을 선택하는 action자체가 action1, action2로 나와야 할것이라고 가설을 세웠는데,
이러면 Q-value가 2중층(?)이 되는것인가 헷갈립니다.

**Comment by yoon-gu** [comment]
액션사이즈는 4가 되는겁니다

**Comment by yoon-gu** [comment]
액션은 다음과 같이 4개입니다.
최대/최소 값은 각각 0,1이라는 가정입니다.

1. (\epsilon=0, \tau=0)
1. (\epsilon=1, \tau=0)
1. (\epsilon=0, \tau=1)
1. (\epsilon=1, \tau=1)
