### ISSUE TITLE
SIR로 강화학습 적용 후 시각화

### ISSUE THREAD

**Issue by yoon-gu** [yoon-gu/epirl#51]
시각화에 들어갈 요소들

0. 시간(t)축으로 S(t), I(t), u(t)
    - `plt.plot(t, S, alpha=0.01)`
1. Value function
2. Policy
3. 학습에 사용된 (S(t), I(t)) Sample path
     - `plt.plot(S(t), I(t), alpha=0.01)`

**Comment by Rabbit739** [comment]
![image](https://user-images.githubusercontent.com/94163977/212102111-10036c32-0951-4089-90b5-fdab50468300.png)
기존 학습은 너무 빨리 이루어져 변화를 보기 어렵다고 판단되어서 변수를 일부 수정하였습니다.
위의 이미지는 2000번 학습 시켰을 때의 결과입니다.

beta: 0.0005
gamma: 0.5
nu: 0.1
tf: 30
S0: 9990
I0: 10

n_episodes: 2000
eps_start: 1.0
eps_end: 0.001
eps_decay: 0.995

제가 현재 reward=-I-action으로 기존 코드와 같이 사용하고 있는데, 기존과 달리 I의 인구수가 5000-6000에 도달하고, 백신 접종 비율을 0.1%로 주다보니 reward가 너무 작은 것처럼 보입니다.
혹시 이런 점을 고려하여 reward를 다시 책정해야 할까요?

**Comment by yoon-gu** [comment]
1. 백신 ratio 앞에 상수는 백신접종비율이 아닙니다. (그냥 ratio의 효과를 낮추는 역할일뿐입니다.)
2. reward가 너무 작은 것처럼 보인다. -> action을 주지 않았을 때와 줬을때의 차이가 적게 난다로 이해했습니다
    - action을 주지 않으면 앞의 infective가 늘어나서 이론상은 별 이슈가 없어보입니다.
3. 혹시 reward가 너무 작다는 의견의 근거가 있으면 알려주시고, reward를 크게 책정해서 실험해보 비교해보세요.
