### ISSUE TITLE
LaTex foreach 구문 질문있습니다.

### ISSUE THREAD

**Issue by Rabbit739** [yoon-gu/epirl#54]
Minyoung\tex\230106doc.tex 파일에서 70~79 line의 foreach 구문중에서
76번째 줄

> \includegraphics[height=0.45\textheight]{../발표 자료/\n result.png}

에서 \n과 result 사이의 띄어쓰기가 인식이 안되는 것 같습니다.

파일 실행시
![image](https://user-images.githubusercontent.com/94163977/211522978-b7238171-b829-4348-b870-f00939f6266f.png)
79번째 줄 }에서 빨간색으로 에러가 이렇게 나타나는데 띄어쓰기 문제가 맞는지, 맞다면 해결할 수 있는 방법이 있는지 궁금합니다.

**Comment by yoon-gu** [comment]
원래 프로그래밍에서는 파일에 공백을 포함하지 않는 것을 기본으로 합니다. (지금 다루고 있는 이슈 외에도 많은 이슈가 발생합니다.)
애초에 공백을 포함하지 않게 파일을 저장하세요.
**앞으로 모든 파일명에 공백을 붙이는건 피해주세요.**

반드시 공백을 포함해야겠다면, 다음 링크를 참조해보세요. (되는지 확인은 안해봤습니다.)
- https://tex.stackexchange.com/questions/8422/how-to-include-graphics-with-spaces-in-their-path

**Comment by Rabbit739** [comment]
넵 감사합니다.
