### ISSUE TITLE
DQN 알고리즘 관련 질문 있습니다.

### ISSUE THREAD

**Issue by Rabbit739** [yoon-gu/epirl#68]
지난 세미나에 발표하던 내용 중, Q_target은 일정 시간이 지난 후에만 업데이트 한다는 내용 관련하여 질문 있습니다.

sir 모델을 DQN으로 돌리는데 필요한 파일에서 step, learn 함수, 그리고 에피소드를 반복하며 학습하는 부분은 다음과 같습니다.

![image](https://user-images.githubusercontent.com/94163977/215405384-eab06925-4d8e-48ff-aec2-06b26d78df5e.png)
![image](https://user-images.githubusercontent.com/94163977/215405418-ee769889-0c39-44c3-9a6f-571f52db2f46.png)
![image](https://user-images.githubusercontent.com/94163977/215405434-f478912f-0c19-4806-9432-55faeecf6442.png)

에피소드를 반복하며 학습을 시작하면 agnet.step(sate, action, reward, next_state, done) 부분에서 step 함수가 실행되고 step 함수를 살펴보면 self.t_step+1 이 update_every의 배수가 되어야만 self.learn 함수가 실행됩니다.
self.learn 함수는 Q_target과 Q_expected 의 값을 계산하여 Q_expected를 업데이트하고 self.soft_update를 통해 Q_target을 업데이트합니다.

제가 이해한 것은 위와 같은데, 그렇다면 일정 간격마다 Q_expected의 업데이트와 Q_target의 업데이트가 동시에 이루어지는게 맞나요?

[23.01.18] DQN 발표자료에 나온 DQN 알고리즘을 보면
![image](https://user-images.githubusercontent.com/94163977/215406297-eb3c09e1-e26c-449e-a593-a05ba91b4023.png)
이와 같은데, 여기서는 Q_expected는 매번 업데이트 되고, Q_target은 일정 간격마다 업데이트 된다고 생각됩니다.

제가 코드 파악을 어느 부분에서 잘못했는지, 아니면 제시된 알고리즘과 코드 구현 방식이 다른 것인지 궁금합니다.

**Comment by yoon-gu** [comment]
말씀하신 사항이 모두 맞습니다. 코드 구현 방식이 해당 논문에 설명된 것과 다릅니다.

논문대로 구현하고 결과를 비교해보세요~!

**Comment by yoon-gu** [comment]
답변이 되었다면 이슈를 Close 해주세요~
