### ISSUE TITLE
알고리즘에 맞게 DQN 모델 수정 및 기존 모델과 비교

### ISSUE THREAD

**Issue by Rabbit739** [yoon-gu/epirl#69]
(이론적인)알고리즘에 맞게 모델 수정하여 제작

기존에 사용하던 모델과 비교하는 작업을 할 예정입니다.

기존 파일은 비교를 위해서 그대로 두고 새롭게 파일을 만들 예정입니다.

**Comment by yoon-gu** [comment]
새로 파일 만들지 마시고 그냥 작업하세요.

예전 알고리즘 비교는 `git checkout`을 사용해서 하면 되니까요

**Comment by Rabbit739** [comment]
넵 알겠습니다!

**Comment by yoon-gu** [comment]
일단 주어진 Psedo 코드대로 구현하고, 비교 실험할 때 궁금한점이 생길테니, 새 코드 구현 업데이트되면 같이 얘기해요!

**Comment by Rabbit739** [comment]
넵!

**Comment by Rabbit739** [comment]
dqn_agent.py 파일 업데이트

- epsilon-greedy part에서 랜덤한 변수를 뽑은 이후 qnetwork에서 argmax한 action을 찾는 경우에만 현재 state에서 action_values 값을 가져오도록 변경 (lines 69~76)

- step 부분에서 EVERY_UPDATE의 배수인 경우에만 learn 하는 것 수정
    - step 실행 시 memory size가 BATCH_SIZE보다 크면 항상 learn으로 넘어가도록 수정 (lines 53~56)
    - learn 파트에서 update target network 부분에 if 문을 넣어 EVERY_UPDATE마다 target network가 업데이트 되도록 변경 (lines 109~111)

위 두 가지 사항이 주어진 Psedo 코드와 다른 것으로 파악되어 수정하였습니다.

**Comment by yoon-gu** [comment]
이거 다 완료한 사항 Pull Request 만들었던가요? 못본거 같아서요
