### ISSUE TITLE
지난 코드 관련 질문 있습니다.

### ISSUE THREAD

**Issue by Rabbit739** [yoon-gu/epirl#72]
현재 sir_rl.py 파일을 새로운 branch에서 pseudo code에 맞게 수정하고 reward에서 백신의 weight를 conf파일에 추가하여 30000번 학습시킨 결과를 얻었습니다. (이미지 파일로 따로 저장했습니다.)

이와 비교를 위해 pseudo code에 맞게 변형하기 전 코드를 이용한 결과를 얻고 싶은데, 63 branch로 들어가서 코드를 살펴보니 현재 비교를 위해서는 몇가지 사항을 수정해야 할 것 같습니다. (vaccine weight나 beta값과 같은 config 파일에서 변수들)

일부 변수들은 command 창에서 hydra를 실행시킬 때 변수에 제가 바꾸고 싶은 할당량을 줘서 코드는 수정하지 않고 실행시킬수도 있을 것 같은데, vaccine weight 같은 경우는 config 파일에 변수로 지정되지 않아서 어떻게 바꿔야 할지 모르겠습니다.

이미 닫힌 branch에서 수정할 수는 없다고 생각되서 어떻게 하면 좋을지 질문 드립니다.

**Comment by yoon-gu** [comment]
질문1. 일부 변수들은 command 창에서 hydra를 실행시킬 때 변수에 제가 바꾸고 싶은 할당량을 줘서 코드는 수정하지 않고 실행시킬수도 있을 것 같은데, vaccine weight 같은 경우는 config 파일에 변수로 지정되지 않아서 어떻게 바꿔야 할지 모르겠습니다.

config 파일에 `vaccine_weight: 1`이런식으로 추가하면 Python 코드에서 `conf.vaccine_weight`로 사용할 수 있습니다.

**Comment by yoon-gu** [comment]
질문2. 이미 닫힌 branch에서 수정할 수는 없다고 생각되서 어떻게 하면 좋을지 질문 드립니다.

> 최신 master에서 브랜치를 만드세요. 현재 이 이슈에서 Create a branch를 하면 되겠네요.

**Comment by Rabbit739** [comment]
그러면 새로 브랜치를 열때 최신기록까지 다 안가져오고, 과거 특정 시점의 데이터를 기반으로 브랜치를 새로 만들면 되나요?
