### ISSUE TITLE
DQN code 비교하기

### ISSUE THREAD

**Issue by Rabbit739** [yoon-gu/epirl#76]
DQN 코드 2가지 버전 비교

**Comment by Rabbit739** [comment]
@yoon-gu 새롭게 branch 생성했습니다
[76-dqn-code-비교하기]
현재 코드에 대한 결과는 바로 얻을 수 있고, 이전 코드에 대한 것은 어떻게 하면 가능하나요???

**Comment by Rabbit739** [comment]
@yoon-gu 
우선 이전코드와 새로 고친 코드를 n_episodes=30000으로 해서 score, SI-vaccine, I-vaccine 그래프를 얻었습니다.
총 2 파트를 바꿨었는데, 첫번째(입실론 그리디에 의한 선택 과정 이후 학습 결과를 필요시에 불러오기)와 두번째(Q_local은 매번 학습, Q_target은 4번마다 업데이트)의 효과를 따로 분리해서 봐야할 것 같습니다.
그래서 총 4가지 버젼의 코드를 저장해둔 후 복원해서 각자 비교를 해보겠습니다!

코드에서 랜덤시드를 고정했는데, 그러면 각 코드를 돌릴때마다 같은 랜덤 숫자가 발생하는게 맞는지 궁금합니다!

**Comment by yoon-gu** [comment]
1번째 버전의 코드를 만들고 커밋 후 실험하고, 2번째 코드 만들고 커밋 후 실험하고......이런식으로 하는게 더 좋겠네요. 이미 다 고쳐서 커밋했으면 어쩔수 없지만요 ㅎㅎ

**Comment by yoon-gu** [comment]
랜덤시드는 설정하면 같은 숫자가 생성되는게 맞긴한데, 그래도 한번 확인해보세요. 동작 안하는 경우도 가끔 있습니다.

여러번 돌려서 계속 같은게 나오면 생각한게 맞을테니까요.

**Comment by Rabbit739** [comment]
넵, 두 파트 모두 작성 후 하나씩 주석처리하며 실험해보려 합니다!

**Comment by Rabbit739** [comment]
우선 4가지 경우를 n_episodes=30000으로 하여 결과를 얻었습니다.
1번째 파트인 랜덤 숫자 뽑기의 순서는 그래프 결과에 아무런 영향이 없었고, 2번째 파트인 qnetwork_local과 qnetwork_target의 업데이트 횟수는 다음과 같이 차이를 보였습니다.

1) local은 매번 업데이트, target은 4번마다 업데이트
![Score_30000](https://user-images.githubusercontent.com/94163977/218936396-f9b3ce4c-2608-418b-93ab-0749276f8df2.png)
![SIR_w_vac_30000](https://user-images.githubusercontent.com/94163977/218936607-d16d460f-dc22-43c9-aced-8d19263fe410.png)

2) local, target모두 4번마다 업데이트
![Score_30000](https://user-images.githubusercontent.com/94163977/218936773-48866d15-a1c8-43e4-a7ff-5fc8df05255a.png)
![SIR_w_vac_30000](https://user-images.githubusercontent.com/94163977/218936804-a953b884-2bed-4e0c-b537-bd2abbe72df2.png)

1번째 파트의 효과는 시간 단축이라고 생각되어서 n_episode를 작게하여 시간을 측정해볼까 합니다. 하나의 버전을 실행시킨 이후, 다른 버전을 실행해야해서 정확한 비교가 가능할지는 모르겠습니다.
또한 랜덤시드를 바꿔서 다른 결과를 얻어볼까 합니다.

**Comment by yoon-gu** [comment]
뭔가 꼭 좋아야할 필요는 없습니다. 이정도 정리하고 발표하고, policy gradient릉 보세요~!
