### ISSUE TITLE
Dqn 수정된 알고리즘 업로드

### ISSUE THREAD

**Issue by yoon-gu** [yoon-gu/epirl#84]

**Comment by Rabbit739** [comment]
rl/dqn에 있는 dqn_agent.py와 sir_rl.py 파일 업데이트 했습니다.
Minyoung 폴더에 있는 dqn_agent.py는 일정 횟수마다 중간 결과가 저장되도록 코드가 약간 바뀌어 있는데, 이 부분은 visualization의 차이라 생각하여 rl/dqn/sir_rl.py에는 반영하지 않았습니다.
더 수정할 사항이 있을까요?

**Comment by yoon-gu** [comment]
코드 수정 부분 볼 수 있게 풀리퀘스트 올린 후 물어봐주세요 ㅎㅎ
